### ISSUE TITLE
LLVM built-in MIPS assembler does not support several FreeBSD kernel assembly idioms

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/llvm#116] opened 2015-06-02 06:00 UTC
Encountered the following trying to assemble the FreeBSD/mips in-kernel exception handler (src/sys/mips/mips/exception.S):

```
...
/home/rnw24/git/llvm/Build/bin/cheri-unknown-freebsd-clang -integrated-as --target=cheri-unknown-freebsd  -msoft-float --sysroot=/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/tmp -c -x assembler-with-cpp -DLOCORE -O -pipe  -g -nostdinc  -I. -I/home/rnw24/git/cheribsd/sys -I/home/rnw24/git/cheribsd/sys/contrib/libfdt -D_KERNEL -DHAVE_KERNEL_OPTION_HEADERS -include opt_global.h  -fno-pic -G0 -DKERNLOADADDR=0xffffffff80100000 -march=mips64 -mabi=64 -msoft-float -ffreestanding -fwrapv -gdwarf-2 -Wall -Wredundant-decls -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Winline -Wcast-qual  -Wundef -Wno-pointer-sign -Wno-format  -Wmissing-include-dirs -fdiagnostics-show-option  -Wno-unknown-pragmas  -Wno-error-tautological-compare -Wno-error-empty-body  -Wno-error-parentheses-equality -Wno-error-unused-function  -Wno-error-pointer-sign    -std=iso9899:1999  -O -pipe  -g -nostdinc  -I. -I/home/rnw24/git/cheribsd/sys -I/home/rnw24/git/cheribsd/sys/contrib/libfdt -D_KERNEL -DHAVE_KERNEL_OPTION_HEADERS -include opt_global.h  -fno-pic -G0 -DKERNLOADADDR=0xffffffff80100000 -march=mips64 -mabi=64 -msoft-float -ffreestanding -fwrapv -gdwarf-2 -Wall -Wredundant-decls -Wnested-externs -Wstrict-prototypes  -Wmissing-prototypes -Wpointer-arith -Winline -Wcast-qual  -Wundef -Wno-pointer-sign -Wno-format  -Wmissing-include-dirs -fdiagnostics-show-option  -Wno-unknown-pragmas  -Wno-error-tautological-compare -Wno-error-empty-body  -Wno-error-parentheses-equality -Wno-error-unused-function  -Wno-error-pointer-sign    -std=iso9899:1999 -D_LOCORE -DLOCORE -Werror /home/rnw24/git/cheribsd/sys/mips/mips/exception.S
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:119:79: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 64f; nop; cmove $c28, $c0; cmove $c0, $c30; 64:
                                                                              ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:119:90: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 64f; nop; cmove $c28, $c0; cmove $c0, $c30; 64:
                                                                                         ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:177:80: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 65f; nop; b 66f; cmove $c0, $c28; 65: cmove $c31, $c29; dmfc0 $26, $14; csetoffset $c31, $c31, $26; 66:
                                                                               ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:198:79: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 64f; nop; cmove $c28, $c0; cmove $c0, $c30; 64:
                                                                              ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:198:90: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 64f; nop; cmove $c28, $c0; cmove $c0, $c30; 64:
                                                                                         ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:467:27: error: '(' expected
 sd $7, ((8 * 4) - 1 * 8) + (40 * 8)($29) # for debugging
                          ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:467:27: error: unexpected token in argument list
 sd $7, ((8 * 4) - 1 * 8) + (40 * 8)($29) # for debugging
                          ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:485:80: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 65f; nop; b 66f; cmove $c0, $c28; 65: cmove $c31, $c29; dmfc0 $26, $14; csetoffset $c31, $c31, $26; 66:
                                                                               ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:662:80: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 65f; nop; b 66f; cmove $c0, $c28; 65: cmove $c31, $c29; dmfc0 $26, $14; csetoffset $c31, $c31, $26; 66:
                                                                               ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:743:27: error: '(' expected
 sd $7, ((8 * 4) - 1 * 8) + (40 * 8)($29) # for debugging
                          ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:743:27: error: unexpected token in argument list
 sd $7, ((8 * 4) - 1 * 8) + (40 * 8)($29) # for debugging
                          ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:757:27: error: '(' expected
 ld $2, ((8 * 4) - 1 * 8) + (40 * 8)($29)
                          ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:757:27: error: unexpected token in argument list
 ld $2, ((8 * 4) - 1 * 8) + (40 * 8)($29)
                          ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:761:80: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 65f; nop; b 66f; cmove $c0, $c28; 65: cmove $c31, $c29; dmfc0 $26, $14; csetoffset $c31, $c31, $26; 66:
                                                                               ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:952:80: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 65f; nop; b 66f; cmove $c0, $c28; 65: cmove $c31, $c29; dmfc0 $26, $14; csetoffset $c31, $c31, $26; 66:
                                                                               ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:1067:80: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 65f; nop; b 66f; cmove $c0, $c28; 65: cmove $c31, $c29; dmfc0 $26, $14; csetoffset $c31, $c31, $26; 66:
                                                                               ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:1075:80: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 65f; nop; b 66f; cmove $c0, $c28; 65: cmove $c31, $c29; dmfc0 $26, $14; csetoffset $c31, $c31, $26; 66:
                                                                               ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:1214:80: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 65f; nop; b 66f; cmove $c0, $c28; 65: cmove $c31, $c29; dmfc0 $26, $14; csetoffset $c31, $c31, $26; 66:
                                                                               ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:1300:10: error: invalid operand for instruction
 beq $7, 0x11, 4f # this should never fail
         ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:1369:79: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 64f; nop; cmove $c28, $c0; cmove $c0, $c30; 64:
                                                                              ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:1369:90: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 64f; nop; cmove $c28, $c0; cmove $c0, $c30; 64:
                                                                                         ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:1404:80: warning: Direct access to c0 is deprecated.
 mfc0 $26, $12; andi $26, $26, 0x00000010; beq $26, $0, 65f; nop; b 66f; cmove $c0, $c28; 65: cmove $c31, $c29; dmfc0 $26, $14; csetoffset $c31, $c31, $26; 66:
                                                                               ^
*** Error code 1

Stop.
make[2]: stopped in /home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/sys/CHERI_DE4_USBROOT
*** Error code 1
```

Disregard $c0 warnings above -- as CHERI gas doesn't yet support CGetDefault and CSetDefault, we are not yet able to eliminate those, but the path to do so is easy.

The two actual errors encountered above are:

(1) FreeBSD appears to use more complex expressions as immediate offsets to load/store instructions than the LLVM assembler supports; e.g.:
```
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:467:27: error: '(' expected
 sd $7, ((8 * 4) - 1 * 8) + (40 * 8)($29) # for debugging
                          ^
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:467:27: error: unexpected token in argument list
 sd $7, ((8 * 4) - 1 * 8) + (40 * 8)($29) # for debugging
```

(2) FreeBSD expects implicit use of $at and an immediate load when passing a constant instead of a register as an argument to a branch instruction:
```
/home/rnw24/git/cheribsd/sys/mips/mips/exception.S:1300:10: error: invalid operand for instruction
 beq $7, 0x11, 4f # this should never fail
         ^
```

**Comment by davidchisnall** [comment] 2015-06-02 10:35
The first is very odd.  It still breaks when you add parentheses, so there's something odd going on with the expression parser.  This may not be a MIPS-specific issue, as the code in the MIPS target is simply asking the assembler to parse an expression.

The second would be better expanded in the asm to use an explicit register to hold the immediate.

**Comment by davidchisnall** [comment] 2015-06-02 12:57
This bug is caused by some ugly hacks in the MIPS asm parser to support ((%lo ...))-style things.  If you can avoid starting with multiple leading brackets then it will work.  I'll see if there's a good solution that doesn't break other things...

**Comment by emaste** [comment] 2015-06-02 13:32
On 2 June 2015 at 02:00, Robert N. M. Watson <notifications@github.com> wrote:
>
> (2) FreeBSD expects implicit use of $at and an immediate load when passing a constant instead of a register as an argument to a branch instruction:
>
> /home/rnw24/git/cheribsd/sys/mips/mips/exception.S:1300:10: error: invalid operand for instruction
>  beq $7, 0x11, 4f # this should never fail

This one is PR22389 https://llvm.org/bugs/show_bug.cgi?id=22389, which
has a patch http://reviews.llvm.org/D9666. I'll see if there's a patch
around to expand these inline already.

**Comment by brooksdavis** [comment] 2015-06-02 15:14
The weird parser bug is https://llvm.org/bugs/show_bug.cgi?id=23697.  It's possible to work around by doing part of the addition in a temporary.  Unfortunately the sd's in exception.S are in branch delay slots so they also need to be partially relocated.

**Comment by davidchisnall** [comment] 2015-06-02 15:23
Looks like we collided in submitting upstream reports.  I've marked yours as a dupe, as mine includes a detailed analysis of the cause.  I can tweak CHERI LLVM quite easily to make this work if we don't use ((%{relocation} ... )) anywhere in immediates (we shouldn't, as it's really stupid).

**Comment by davidchisnall** [comment] 2015-10-27 11:58
These are probably all fixed by the upstream merge.  Please retest once it's committed.

**Closed** 2015-11-30 20:25 UTC
