### ISSUE TITLE
CHERI 128-bit LLVM backend crash: fatal error: error in backend: Cannot select: 0x806f08dd0: iFATPTR = addrspacecast[0 -> 200] 0x806ee8e38

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/llvm#235] opened 2017-08-14 16:46 UTC
In attempting (probably improperly) to compile the CheriBSD 128-bit kernel using CHERI Clang/LLVM, I encountered the following crash. This is with fresh SDK parts built this morning, which are able to build a current CheriBSD world:

```
/home/rnw24/sdk256/sdk/bin/clang -c -O -pipe  -g -nostdinc  -I. -I/home/rnw24/git/cheribsd/sys -I/home/rnw24/git/cheribsd/sys/contrib/libfdt -D_KERNEL -DHAVE_KERNEL_OPTION_HEADERS -include opt_global.h  -fno-pic -mno-abicalls -G0 -DKERNLOADADDR=0xffffffff80100000 -target cheri-unknown-freebsd -march=mips64 -mabi=64 -MD  -MF.depend.scsi_da.o -MTscsi_da.o -msoft-float -ffreestanding -fwrapv -gdwarf-2 -Wall -Wredundant-decls -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Winline -Wcast-qual -Wundef -Wno-pointer-sign -D__printf__=__freebsd_kprintf__ -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unknown-pragmas -Wno-error-tautological-compare -Wno-error-empty-body -Wno-error-parentheses-equality -Wno-error-unused-function -Wno-error-pointer-sign -Wno-error-shift-negative-value -Wno-error-address-of-packed-member    -std=iso9899:1999 -Werror  /home/rnw24/git/cheribsd/sys/cam/scsi/scsi_da.c
fatal error: error in backend: Cannot select: 0x806f08dd0: iFATPTR = addrspacecast[0 -> 200] 0x806ee8e38
  0x806ee8e38: i64,ch = load<LD8[@zero_region](tbaa=<0x80669d328>)(dereferenceable)> 0x806b2d030, 0x806f45138, undef:i64
    0x806f45138: i64 = add 0x806ee8a90, 0x8070cb000
      0x806ee8a90: i64 = shl 0x806f08270, Constant:i32<16>
        0x806f08270: i64 = add 0x8070cb6e8, 0x806fdb548
          0x8070cb6e8: i64 = shl 0x806e753a8, Constant:i32<16>
            0x806e753a8: i64 = add 0x806ee8820, 0x806f40618
              0x806ee8820: i64 = MipsISD::Highest TargetGlobalAddress:i64<i8** @zero_region> 0 [TF=19]
                0x806e759c0: i64 = TargetGlobalAddress<i8** @zero_region> 0 [TF=19]
              0x806f40618: i64 = MipsISD::Higher TargetGlobalAddress:i64<i8** @zero_region> 0 [TF=18]
                0x806ee8618: i64 = TargetGlobalAddress<i8** @zero_region> 0 [TF=18]
            0x806f40138: i32 = Constant<16>
          0x806fdb548: i64 = MipsISD::Hi TargetGlobalAddress:i64<i8** @zero_region> 0 [TF=4]
            0x806ee8888: i64 = TargetGlobalAddress<i8** @zero_region> 0 [TF=4]
        0x806f40138: i32 = Constant<16>
      0x8070cb000: i64 = MipsISD::Lo TargetGlobalAddress:i64<i8** @zero_region> 0 [TF=5]
        0x806fdbc30: i64 = TargetGlobalAddress<i8** @zero_region> 0 [TF=5]
    0x806fdb9c0: i64 = undef
In function: da_delete_ws
clang-5.0: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 5.0.0 (https://github.com/CTSRD-CHERI/clang 9f753d362e07e48c123ceb16a6334ddf39b0f5d8) (http://github.com/CTSRD-CHERI/llvm 63e7e699f10d9856d95e9b15e8e4d1871d595872)
Target: cheri-unknown-freebsd
Thread model: posix
InstalledDir: /home/rnw24/sdk256/sdk/bin
clang-5.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-5.0: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-5.0: note: diagnostic msg: /tmp/scsi_da-d77ca6.c
clang-5.0: note: diagnostic msg: /tmp/scsi_da-d77ca6.sh
clang-5.0: note: diagnostic msg: 

********************
*** Error code 70

Stop.
bmake[2]: stopped in /home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/sys/CHERI_MALTA64
*** Error code 1

Stop.
bmake[1]: stopped in /home/rnw24/git/cheribsd
*** Error code 1

Stop.
make: stopped in /home/rnw24/git/cheribsd
```

It is not urgent that this file be able to compile with CHERI Clang/LLVM, as user error is the only reason it is trying to compile .. on the other hand, a reproducible bug.

Gists of the two output files from Clang:
scsi_da-d77ca6.c : https://gist.github.com/rwatson/89d644a6dfe42b3b62698184b5b005cf
scsi_da-d77ca6.sh: https://gist.github.com/rwatson/28ccd884ce6d86b6846cdfae06be0569

**Comment by RichardsonAlex** [comment] 2017-08-15 08:51
I can't reproduce this, if I use the command line unchanged I get the error 
`Trying to compile CHERI256 code with a CHERI128 compiler!`. Clang assumes any mcpu=foo other that =cheri128 without `-mllvm -cheri128` implies cheri256 (we should probably fix that and just set the default to cheri128 for the 128 build).
If I add that option I get the following:
```
In file included from /home/rnw24/git/cheribsd/sys/cam/scsi/scsi_da.c:32:
In file included from /home/rnw24/git/cheribsd/sys/sys/param.h:135:
In file included from ./machine/param.h:50:
In file included from ./machine/cpu.h:65:
In file included from ./machine/frame.h:70:
In file included from /home/rnw24/git/cheribsd/sys/cheri/cheri.h:224:
./machine/cheri.h:127:1: error: static_assert failed "compile-time assertion failed"
CTASSERT(sizeof(struct cheri_frame) == (29 * CHERICAP_SIZE));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rnw24/git/cheribsd/sys/sys/systm.h:105:21: note: expanded from macro 'CTASSERT'
#define CTASSERT(x)     _Static_assert(x, "compile-time assertion failed")
```

**Comment by davidchisnall** [comment] 2018-03-02 11:51
Closing as this looks as if it was user error, please reopen if it wasn't.

**Closed by davidchisnall** 2018-03-02 11:51 UTC
Labels: CHERI128, bug
