### ISSUE TITLE
va_copy in a loop results in stack access via DDC

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#240] opened 2017-09-18 19:54 UTC
When compiled at `-O2` in pure capability mode, this code snippet attempts to access the stack via DDC.
```C
#include <stdarg.h>

int a_func_taking_a_va_list(va_list l);

void a_func(int foo, ...)
{
        va_list va;

        va_start(va, foo);
        for (;;) {
                va_list copy;
                va_copy(copy, va);
                if (a_func_taking_a_va_list(copy))
                        return;
                va_end(copy);
        }
        va_end(va);
}
```
This produces:
```
$ clang --target=cheri-unknown-freebsd -mabi=purecap ~/va_copy.c -O2 -S -o /dev/stdout
```
This produces the following (truncated) output with the bad accesses starting at `BB#1`:
```
# BB#0:
        daddiu  $sp, $sp, -192
        csd     $fp, $sp, 184($c11)     # 8-byte Folded Spill
        csd     $gp, $sp, 176($c11)     # 8-byte Folded Spill
        csd     $17, $sp, 168($c11)     # 8-byte Folded Spill
        csd     $16, $sp, 160($c11)     # 8-byte Folded Spill
        csc     $c19, $sp, 128($c11)    # 32-byte Folded Spill
        csc     $c18, $sp, 96($c11)     # 32-byte Folded Spill
        csc     $c17, $sp, 64($c11)     # 32-byte Folded Spill
        move     $fp, $sp
        cgetoffset      $25, $c12
        lui     $1, %hi(%neg(%gp_rel(a_func)))
        daddu   $1, $1, $25
        daddiu  $gp, $1, %lo(%neg(%gp_rel(a_func)))
        daddiu  $1, $fp, 32
        csetoffset      $c1, $c11, $1
        daddiu  $1, $zero, 32
        csetbounds      $c19, $c1, $1
        daddiu  $2, $fp, 0
        csetoffset      $c1, $c11, $2
        csetbounds      $c18, $c1, $1
        csc     $c13, $zero, 0($c19)
        csc     $c13, $zero, 0($c18)
        ld      $1, %call16(a_func_taking_a_va_list)($gp)
        cgetpccsetoffset        $c12, $1
        cjalr   $c12, $c17
        cincoffset      $c3, $c13, $zero
        bnez    $2, .LBB0_3
        nop
# BB#1:
        ctoptr $16, $c19, $c0
        ctoptr $17, $c18, $c0
.LBB0_2:                                # =>This Inner Loop Header: Depth=1
        clc     $c1, $16, 0($c0)
        csc     $c1, $17, 0($c0)
        clc     $c3, $zero, 0($c18)
        ld      $1, %call16(a_func_taking_a_va_list)($gp)
        cgetpccsetoffset        $c12, $1
        cjalr   $c12, $c17
        nop
        beqz    $2, .LBB0_2
        nop
...
```
This breaks csh in `xasprintf()` if DCC doesn't cover the stack.

**Comment by davidchisnall** [comment] 2017-09-19 09:24
Useable test case:

```c
#define va_start(v,l) __builtin_va_start((v),l)
#define va_end __builtin_va_end
#define va_arg __builtin_va_arg
#define va_copy __builtin_va_copy
typedef __builtin_va_list>--va_list;

int a_func_taking_a_va_list(va_list l);


void a_func(int foo, ...)
{
        va_list va;
        va_start(va, foo);
        for (;;) {
                va_list copy;
                va_copy(copy, va);
                a_func_taking_a_va_list(copy);
                va_end(copy);
        }
        va_end(va);
}
```

It's apparent from the IR what the problem is:

```llvm
  call void @llvm.va_start(i8* nonnull %va1)
  %1 = bitcast i8 addrspace(200)* addrspace(200)* %copy to i8 addrspace(200)*
  %2 = addrspacecast i8 addrspace(200)* %1 to i8*
```

In a single basic block, SelectionDAG is able to look through the cast, but it isn't in the version with flow control in the middle.  This ends up with a `ctoptr` being generated for the `addrspacecast`.  The fix for this is going to require making all of the variadic intrinsics overloaded.

**Closed** 2017-09-19 11:27 UTC
Labels: bug, CHERIABI
