### ISSUE TITLE
Problem with CheriOS assert.

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/llvm#196] opened 2017-03-13 13:03 UTC
Trying to build CheriOS fails with:

fatal error: error in backend: Cannot select: 0x805a896e8: ch = store<ST8[<unknown>]> 0x805a89138, 0x805a8a208, 0x805a89680, undef:iFATPTR
  0x805a8a208: i64,ch = load<LD4[%7(addrspace=200)](dereferenceable), sext from i32> 0x805a86b60, FrameIndex:i64<2>, undef:i64
    0x805a86a28: i64 = FrameIndex<2>
    0x805a86888: i64 = undef
  0x805a89680: iFATPTR = MipsISD::STACKTOCAP 0x805a89618
    0x805a89618: i64 = add 0x805a89208, Constant:i64<64>
      0x805a89208: i64,ch = CopyFromReg 0x805a89138, Register:i64 %SP_64
        0x805a891a0: i64 = Register %SP_64
      0x805a895b0: i64 = Constant<64>
  0x805a892d8: iFATPTR = undef
In function: __assert

https://gist.github.com/trasz/498f0fe597eec89548f54d050c94259f

**Comment by davidchisnall** [comment] 2017-03-21 10:58
Is this a duplicate of #195?

**Comment by trasz** [comment] 2017-03-21 11:08
Perhaps not a strict duplicate, but yeah, caused by the same problem (-march=mips4 or -mcpu=mips4, don't remember which).

**Closed** 2017-03-21 11:10 UTC
Labels: bug, duplicate
