### ISSUE TITLE
Integrated assembler not marking functions correctly

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#165] opened 2016-05-12 16:47 UTC
Consider a minimal assembly function:
```
.text
.globl  foo
.ent    foo
foo:
        jr ra
.end    foo
```
Compiled with gas, the `foo` symbol is a function:
```
$ elfdump -s func.o
...
entry: 6
        st_name: foo
        st_value: 0
        st_size: 8
        st_info: STT_FUNC STB_GLOBAL
        st_shndx: 1
```

With clang and integrated assembler, it's untyped
```
$ clang -g -integrated-as --target=cheri-unknown-freebsd  -msoft-float --sysroot=/home/bed22/obj/mips.mips64/home/bed22/git/cheribsd/tmp -mabi=sandbox -mxgot -cheri-linker -c func.S
$ elfdump -s func.o
...
entry: 5
        st_name: foo
        st_value: 0
        st_size: 0
        st_info: STT_NOTYPE STB_GLOBAL
        st_shndx: 2
```

I think this is the cause of problems I'm seeing in rtfd-cheri-elf where __sys_openat isn't a function when assigned to the interposer table and thus I get permit-exec exceptions when trying to open files.

**Comment by davidchisnall** [comment] 2016-05-13 08:15
This appears to be caused by not marking the function with the correct attribute.  The function should include:

```asm
.type	foo,@function
```

The assembler should not be assuming that things are functions unless told they are.  The Objective-C runtime, for example, includes some trampolines that are copied into executable memory but would not want them to be marked as functions simply because they contain instructions.

**Closed by davidchisnall** 2016-05-13 08:15 UTC
Labels: CHERIABI
