### ISSUE TITLE
Assertion failure compiling purecap kernel code "Can't find reaching def for virtreg"

### ISSUE THREAD

**Issue by qwattash** [CTSRD-CHERI/llvm#245] opened 2017-09-25 14:16 UTC
Assertion failure when attempting to compile purecap kernel code from vfs_cache. This occurs on the master branch of both llvm and clang.

Stacktrace:
```
Assertion failed: (MBB != &MF->front() && "Can't find reaching def for virtreg"), function MarkVirtRegAliveInBlock, file /home/am2419/git/llvm/lib/CodeGen/LiveVariables.cpp, line 114.                                                        
#0 0x000000000362eddc llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/am2419/git/llvm/lib/Support/Unix/Signals.inc:398:11                                                                                                                 
#1 0x000000000362f2a6 __assert /home/am2419/git/llvm/lib/Support/Unix/Signals.inc:486:3                                
#2 0x000000000270f6de llvm::LiveVariables::MarkVirtRegAliveInBlock(llvm::LiveVariables::VarInfo&, llvm::MachineBasicBlock*, llvm::MachineBasicBlock, std::__1::vector<llvm::MachineBasicBlock, llvm::MachineBasicBlock*::allocator<llvm::MachineBasicBlock> >&) /home/am2419/git/llvm/lib/CodeGen/LiveVariables.cpp:0:3                                               
#3 0x000000000270f931 llvm::LiveVariables::MarkVirtRegAliveInBlock(llvm::LiveVariables::VarInfo&, llvm::MachineBasicBlock*, llvm::MachineBasicBlock) /home/am2419/git/llvm/lib/CodeGen/LiveVariables.cpp:0:3                                   
#4 0x000000000271017e llvm::LiveVariables::HandleVirtRegUse(unsigned int, llvm::MachineBasicBlock*, llvm::MachineInstr&) /home/am2419/git/llvm/lib/CodeGen/LiveVariables.cpp:0:5                                                               
#5 0x000000000271271c llvm::LiveVariables::runOnInstr(llvm::MachineInstr&, llvm::SmallVectorImpl<unsigned int>&) /home/am2419/git/llvm/lib/CodeGen/LiveVariables.cpp:546:7                                                                     
#6 0x0000000002712dbc llvm::LiveVariables::runOnBlock(llvm::MachineBasicBlock*, unsigned int) /home/am2419/git/llvm/lib/CodeGen/LiveVariables.cpp:0:5                                                                                          
#7 0x000000000271359b llvm::LiveVariables::runOnMachineFunction(llvm::MachineFunction&) /home/am2419/git/llvm/lib/CodeGen/LiveVariables.cpp:649:5                                                                                              
#8 0x000000000279e441 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/am2419/git/llvm/lib/CodeGen/MachineFunctionPass.cpp:62:8                                                                                                 
#9 0x0000000002cdfb5f llvm::FPPassManager::runOnFunction(llvm::Function&) /home/am2419/git/llvm/lib/IR/LegacyPassManager.cpp:1522:27                                                                                                           
#10 0x0000000002cdfe75 llvm::FPPassManager::runOnModule(llvm::Module&) /home/am2419/git/llvm/lib/IR/LegacyPassManager.cpp:1544:16                                                                                                              
#11 0x0000000002ce0b78 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/am2419/git/llvm/lib/IR/LegacyPassManager.cpp:1600:27                                                                                             
#12 0x0000000002ce0136 llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/am2419/git/llvm/lib/IR/LegacyPassManager.cpp:1703:16                                                                                                            
#13 0x0000000002ce1761 llvm::legacy::PassManager::run(llvm::Module&) /home/am2419/git/llvm/lib/IR/LegacyPassManager.cpp:1734:3                                                                                                                 
#14 0x0000000003999771 (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, clang::BackendAction::default_delete<llvm> >) /home/am2419/git/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:812:19                                     
#15 0x0000000003994d21 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, clang::LangOptions const&::Module*, clang::BackendAction, std::__1::unique_ptr<clang::LangOptions const&::raw_pwrite_stream, clang::BackendAction::default_delete<std::__1::unique_ptr> >) /home/am2419/git/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:1121:15 
#16 0x00000000048f19a8 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /home/am2419/git/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:258:7                                                                                 
#17 0x0000000005a3cd97 clang::ParseAST(clang::Sema&, bool, bool) /home/am2419/git/llvm/tools/clang/lib/Parse/ParseAST.cpp:159:13                                                                                                               
#18 0x000000000423f285 clang::ASTFrontendAction::ExecuteAction(void) /home/am2419/git/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:940:1                                                                                                   
#19 0x00000000048ec79e clang::CodeGenAction::ExecuteAction(void) /home/am2419/git/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:991:1                                                                                                         
#20 0x000000000423e870 clang::FrontendAction::Execute(void) /home/am2419/git/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:842:7                                                                                                            
#21 0x000000000418e6fe clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/am2419/git/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:971:7                                                                                
#22 0x00000000043f8582 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/am2419/git/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:249:8                                                                       
#23 0x0000000000a608d0 char const* cc1_main(llvm::ArrayRef<char const*>(void*) /home/am2419/git/llvm/tools/clang/tools/driver/cc1_main.cpp:221:11                                                                                              
#24 0x0000000000a4eec9 llvm::StringRef ExecuteCC1Tool(llvm::ArrayRef<char const*>() /home/am2419/git/llvm/tools/clang/tools/driver/driver.cpp:299:5                                                                                            
#25 0x0000000000a4ca83 main /home/am2419/git/llvm/tools/clang/tools/driver/driver.cpp:380:5                            
#26 0x0000000000a4b02f _start (/home/am2419/git/build/llvm-master/bin/clang-5.0+0xa4b02f)
```

Clang output files:
[vfs_cache-cfa979.c](https://gist.github.com/qwattash/4e6d6b84e7bfcf3fbec1f12ec5fc7d39)
[vfs_cache-cfa979.sh](https://gist.github.com/qwattash/cdbac3f6fe423c5ba3a79d107734cec4)
Reduced test case:
[vfs_cache-cfa979-reduced.c](https://gist.github.com/qwattash/5a0a2018c0aaf55c4ec2829a90c8c8e3)

**Comment by RichardsonAlex** [comment] 2017-09-25 14:25
I can't reproduce this on the dev branch, so it seems like it has been fixed in the upstream merge.

**Comment by qwattash** [comment] 2017-09-25 15:58
Just tested it, the issue seems to be fixed in the dev branch.

**Comment by arichardson** [comment] 2018-02-19 13:16
Looking at the machine code it seems like register %6 is in a different block for some reason
```
# *** IR Dump Before Live Variable Analysis ***:
# Machine code for function b: IsSSA, TracksLiveness
Function Live Ins: $c12

bb.0.entry:
  liveins: $c12
  successors: %bb.1(0x40000000), %bb.2(0x40000000); %bb.1(50.00%), %bb.2(50.00%)
  $t9_64 = CGetOffset $c12
  %7:gpr64 = LUi64 target-flags(mips-gpoff-hi) @b
  %8:gpr64 = DADDu %7, $t9_64
  BNE killed $zero, $zero, %bb.2, implicit-def $at

bb.1:
  successors: %bb.3(0x80000000); %bb.3(200.00%)
; predecessors: %bb.0
  %1:gpr64 = DADDiu %8, target-flags(mips-gpoff-lo) @b
  %2:gpr64 = LD %1, target-flags(mips-got-page) @a, implicit $c0; mem:LD8[GOT]
  %5:gpr32 = LW %2, target-flags(mips-got-ofst) @a, implicit $c0
  SW64 %6, %2, target-flags(mips-got-ofst) @a, implicit $c0
  B %bb.3, implicit-def $at

bb.2.if.then:
; predecessors: %bb.0
  CapRetPseudo

bb.3.c:
  successors: %bb.3(0x80000000); %bb.3(200.00%)
; predecessors: %bb.3, %bb.1
  %6:gpr32 = ADDiu killed %5, 1
  B %bb.3, implicit-def dead $at

# End machine code for function b.
```

**Comment by arichardson** [comment] 2018-02-19 13:18
The CheriAddressingModeFolder is moving intstructions to a different basic block which is causing this assertion:
```
# *** IR Dump Before Cheri Addressing Mode Folder ***:
# Machine code for function b: IsSSA, TracksLiveness
Function Live Ins: $c12

bb.0.entry:
  liveins: $c12
  successors: %bb.4(0x40000000), %bb.2(0x40000000); %bb.4(50.00%), %bb.2(50.00%)
  $t9_64 = CGetOffset $c12
  %7:gpr64 = LUi64 target-flags(mips-gpoff-hi) @b
  %8:gpr64 = DADDu %7, $t9_64
  BNE killed $zero, $zero, %bb.2, implicit-def $at

bb.4:
  successors: %bb.3(0x80000000); %bb.3(200.00%)
; predecessors: %bb.0
  %1:gpr64 = DADDiu %8, target-flags(mips-gpoff-lo) @b
  %2:gpr64 = LD %1, target-flags(mips-got-page) @a, implicit $c0; mem:LD8[GOT]
  %3:gpr64 = DADDiu %2, target-flags(mips-got-ofst) @a
  %4:cheriregs = CFromPtr $c0, %3
  B %bb.3, implicit-def $at

bb.2.if.then:
; predecessors: %bb.0
  CapRetPseudo

bb.3.c:
  successors: %bb.3(0x80000000); %bb.3(200.00%)
; predecessors: %bb.3, %bb.4
  %5:gpr32 = CAPLOAD32 $zero_64, 0, %4; mem:LD4[@a(addrspace=200)](dereferenceable)
  %6:gpr32 = ADDiu killed %5, 1
  CAPSTORE32 killed %6, $zero_64, 0, %4; mem:ST4[@a(addrspace=200)]
  B %bb.3, implicit-def dead $at

# End machine code for function b.

# *** IR Dump Before Cheri128 fail hard ***:
# Machine code for function b: IsSSA, TracksLiveness
Function Live Ins: $c12

bb.0.entry:
  liveins: $c12
  successors: %bb.4(0x40000000), %bb.2(0x40000000); %bb.4(50.00%), %bb.2(50.00%)
  $t9_64 = CGetOffset $c12
  %7:gpr64 = LUi64 target-flags(mips-gpoff-hi) @b
  %8:gpr64 = DADDu %7, $t9_64
  BNE killed $zero, $zero, %bb.2, implicit-def $at

bb.4:
  successors: %bb.3(0x80000000); %bb.3(200.00%)
; predecessors: %bb.0
  %1:gpr64 = DADDiu %8, target-flags(mips-gpoff-lo) @b
  %2:gpr64 = LD %1, target-flags(mips-got-page) @a, implicit $c0; mem:LD8[GOT]
  %5:gpr32 = LW %2, target-flags(mips-got-ofst) @a, implicit $c0
  SW64 %6, %2, target-flags(mips-got-ofst) @a, implicit $c0
  B %bb.3, implicit-def $at

bb.2.if.then:
; predecessors: %bb.0
  CapRetPseudo

bb.3.c:
  successors: %bb.3(0x80000000); %bb.3(200.00%)
; predecessors: %bb.3, %bb.4
  %6:gpr32 = ADDiu killed %5, 1
  B %bb.3, implicit-def dead $at

# End machine code for function b.
```

**Comment by davidchisnall** [comment] 2018-02-19 17:34
What branch is the test in?  It doesn't seem to be master and GitHub doesn't provide a way of going from commit to the containing branches.

**Comment by arichardson** [comment] 2018-02-19 19:29
It's in the dev branch

**Comment by arichardson** [comment] 2018-02-19 19:31
I've cherry-picked it to master since it is also an issue there, we were just not generating the crashing IR from the C source code.

**Closed** 2018-02-20 14:57 UTC
Labels: bug
