### ISSUE TITLE
llvm-objdump crash

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/llvm#202] opened 2017-03-21 12:28 UTC
Trying to do "llvm-objdump -S -d -r -s git/postgres/src/backend/postgres" (binary would be attached, if it weren't too big; it's on thyme.cl.cam.uk in ~en322/) results in segfault.

```
; [New Thread 802e16000 (LWP 100596/llvm-objdump)]

Program received signal SIGBUS, Bus error.
[Switching to Thread 802e16000 (LWP 100596/llvm-objdump)]
llvm::StringRef::find_first_not_of (this=0x807a606f0, Chars={static npos = <optimized out>, Data = 0x11acc " \t\n\v\f\r", Length = 6}, From=0) at /home/en322/cheri/llvm/lib/Support/StringRef.cpp:283
283         if (!CharBits.test((unsigned char)Data[i]))
(gdb) where
#0  llvm::StringRef::find_first_not_of (this=0x807a606f0, Chars={static npos = <optimized out>, Data = 0x11acc " \t\n\v\f\r", Length = 6}, From=0) at /home/en322/cheri/llvm/lib/Support/StringRef.cpp:283
#1  0x0000000000737f66 in llvm::StringRef::ltrim (this=0x807a606f0, Chars={static npos = <optimized out>, Data = 0x11acc " \t\n\v\f\r", Length = 6}) at StringRef.h:813
#2  0x000000000070bc53 in (anonymous namespace)::SourcePrinter::printSourceLine (this=0x7fffffffa810, OS=@0x17de690, Address=4852098196, Delimiter={static npos = <optimized out>, Data = 0x1111b "; ", Length = 2})
    at /home/en322/cheri/llvm/tools/llvm-objdump/llvm-objdump.cpp:494
#3  0x00000000006f3054 in (anonymous namespace)::PrettyPrinter::printInst (this=0x1438028, IP=@0x802e316f0, MI=0x7fffffff9e90, Bytes={Data = 0x804352494 "\003b213I", Length = 4}, Address=4852098196, OS=@0x17de690, Annot=
      {static npos = <optimized out>, Data = 0x102b8 "", Length = 0}, STI=@0x802e27180, SP=0x7fffffffa810) at /home/en322/cheri/llvm/tools/llvm-objdump/llvm-objdump.cpp:518
#4  0x00000000007082bf in DisassembleObject (Obj=0x802e70000, InlineRelocs=true) at /home/en322/cheri/llvm/tools/llvm-objdump/llvm-objdump.cpp:1584
#5  0x00000000006ff901 in DumpObject (o=0x802e70000, a=0x0) at /home/en322/cheri/llvm/tools/llvm-objdump/llvm-objdump.cpp:2086
#6  0x00000000006f2e38 in DumpInput (file={static npos = <optimized out>, Data = 0x802e1fb81 "src/backend/postgres", Length = 20}) at /home/en322/cheri/llvm/tools/llvm-objdump/llvm-objdump.cpp:2177
#7  0x00000000006f2c9c in main (argc=6, argv=0x7fffffffe9a0) at algorithm:859


```

**Comment by davidchisnall** [comment] 2017-03-21 13:56
I can't reproduce this with the latest llvm.

**Comment by davidchisnall** [comment] 2017-03-21 16:54
Comment from @trasz: This bug only manifests if the source code is visible, so it appears to be something missing some checks in the code that @emaste wrote to interleave source and disassembly.

**Comment by davidchisnall** [comment] 2018-03-02 14:22
@emaste Was this fixed with some upstream changes?

**Comment by arichardson** [comment] 2019-03-13 15:09
Should be fixed.

**Closed by arichardson** 2019-03-13 15:09 UTC
Labels: bug, works for me
