### ISSUE TITLE
String arrays not handled by current linking

### ISSUE THREAD

**Issue by hbcam** [CTSRD-CHERI/llvm#168] opened 2016-06-16 10:22 UTC
String arrays are not handled nicely by capsizefix.

```
const char * s[] = {
    "A",
    "B",
    "C"
};

int main(void) {
    return 0;
}
```

gives this kind of warnings: `Unable to find size of symbol at XXX for pointer at 0xXXX
Using section size (XXX bytes) instead`

The future real cheri-linker should handle such cases.

**Comment by davidchisnall** [comment] 2016-07-13 13:10
This is caused by the fact that we run the thing that sets the size after we have done linking.  The strings have private linkage and so their symbol information is gone by the time that we run `capsizefix`.  We could possibly fix this by doing an initial run of `capsizefix` for each compilation unit.

**Comment by davidchisnall** [comment] 2018-03-02 14:27
I believe that this is fixed by the captable branch, but it would be good to test.

**Comment by arichardson** [comment] 2018-03-02 16:29
Fixed in master, better solution in cap-table

**Closed by arichardson** 2018-03-02 16:29 UTC
Labels: bug, cheri-linker
